package response

import (
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// StandardResponse defines the standard API response structure.
type StandardResponse struct {
	Code     int         `json:"code"`
	Data     interface{} `json:"data,omitempty"`
	Message  string      `json:"message"`
	SourceID string      `json:"sourceId"`
	TraceID  string      `json:"traceId"`
}

// getTraceAndSourceID retrieves traceId from the client request header
// and generates a new sourceId for the response.
func getTraceAndSourceID(c *gin.Context) (string, string) {
	// traceId must be passed from the client via "X-Trace-ID" header.
	traceID := c.GetHeader("X-Trace-ID")

	// sourceId is generated by the server for each response.
	sourceID := uuid.New().String()[:8]

	return traceID, sourceID
}

// Success sends a standard success response.
func Success(c *gin.Context, httpStatus int, data interface{}) {
	traceID, sourceID := getTraceAndSourceID(c)
	c.JSON(httpStatus, StandardResponse{
		Code:     0, // Success code is always 0
		Data:     data,
		Message:  "OK",
		SourceID: sourceID,
		TraceID:  traceID,
	})
}

// Error sends a standard error response.
func Error(c *gin.Context, httpStatus int, code int, message string, err error) {
	traceID, sourceID := getTraceAndSourceID(c)

	fullMessage := message
	if err != nil {
		fullMessage = fmt.Sprintf("%s: %v", message, err)
	}

	c.JSON(httpStatus, StandardResponse{
		Code:     code,
		Message:  fullMessage,
		SourceID: sourceID,
		TraceID:  traceID,
	})
}
